In [0]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression, RidgeClassifierCV, Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [0]:
X_train = np.array(pd.read_csv('/content/OzoneTrain.csv', header = None))
y_train = np.array(pd.read_csv('/content/LabelTrain.csv', header = None))

In [0]:
X_test= np.array(pd.read_csv('/content/OzoneTest.csv', header = None))
y_test = np.array(pd.read_csv('/content/LabelTest-2.csv', header = None))


In [70]:
#Logistic_regression
lr = LogisticRegression(penalty = 'none', max_iter = 1000)
lr.fit(X_train, y_train.reshape(1539,))
y_pred = lr.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [71]:
### Confusion matrix for test set
lr_cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix of Logistic Regression : ",lr_cm)
print()
print("Accuracy score of Logistic Regression : ", accuracy_score(y_test, y_pred))
print()
print("Coefficient_ :", lr.coef_)

Confusion matrix of Logistic Regression :  [[275   2]
 [ 17   6]]

Accuracy score of Logistic Regression :  0.9366666666666666

Coefficient_ : [[-0.10579905 -0.11812641 -0.07043869  0.17383292  0.26015679  0.28417304
   0.21491645  0.13884055 -0.08255845 -0.13673253 -0.25470681 -0.23395872
  -0.23086725 -0.14092479 -0.04920921 -0.02371339 -0.02347822  0.25560538
   0.23913208  0.13319999  0.13078752 -0.05623801 -0.22572527 -0.3167455
  -0.14015525 -0.00656727  0.1144458   0.05557769  0.06544491 -0.09410847
  -0.2407567  -0.2464128  -0.14978644 -0.01503802  0.04444123  0.11072759
   0.16404719  0.13456762  0.05580188  0.15594479  0.12401274  0.01716221
  -0.10035019 -0.05171264 -0.0124687   0.03264287  0.09573507  0.12615831
   0.0609593  -0.02236997 -0.08842369  0.02030818  0.10107933 -0.00968053
  -0.04248953 -0.10677203  0.01603268 -0.00842246 -0.00987241 -0.0210462
   0.03526433 -0.0196838   0.01624143 -0.05924809  0.05712875  0.0130122
  -0.00198182 -0.04750786  0.06547024  0.00316

In [72]:
## Ridge Regression
ridge = RidgeClassifierCV(alphas = (0.1, 1, 10, 100), store_cv_values= True)
ridge.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_ridge.py:1853: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


RidgeClassifierCV(alphas=array([  0.1,   1. ,  10. , 100. ]), class_weight=None,
                  cv=None, fit_intercept=True, normalize=False, scoring=None,
                  store_cv_values=True)

In [0]:
y_pred_ridge = ridge.predict(X_test)

In [76]:
print("Alpha of Ridge Regression", ridge.alpha_)
print()
print("Confusion matrix of Ridge Regresison", confusion_matrix(y_test, y_pred_ridge))
print()
print("Accuracy score of Ridge Regression", accuracy_score(y_test, y_pred_ridge))
print()
print(" Ridge Regression Coefficients", ridge.coef_)

Alpha of Ridge Regression 100.0

Confusion matrix of Ridge Regresison [[277   0]
 [ 23   0]]

Accuracy score of Ridge Regression 0.9233333333333333

 Ridge Regression Coefficients [[ 0.00154429 -0.01354504 -0.01992213  0.02582503  0.03137703  0.02707451
   0.03331368  0.02133993 -0.03030042 -0.00900187 -0.02808244 -0.01744116
  -0.01406997 -0.00822947 -0.00373334 -0.0019859  -0.01557541  0.04057878
   0.0136257  -0.00166283  0.02494973  0.00552435 -0.01790296 -0.01865395
  -0.01149395  0.00501502  0.00780676 -0.01286169  0.02069466 -0.01367127
  -0.03130145 -0.00835243 -0.03970614  0.0317349   0.01569593  0.0103677
   0.00362729  0.00341209 -0.01659578  0.00968036  0.01544087  0.02112392
  -0.02999872  0.0009682   0.00474361 -0.00830879  0.00421197  0.01963274
   0.00497841 -0.02370856  0.0058671   0.00044865  0.01502921 -0.00568211
  -0.00288192 -0.01273078  0.01023451  0.01703592 -0.00488151 -0.00452804
   0.00094629 -0.00419605  0.01253693 -0.02877756  0.00521055  0.0024189
  -0.001

In [80]:
## Lasso
lasso = LogisticRegression(penalty = 'l2', max_iter = 1000)
param = {'C':[0.1, 1, 10, 100]}
tune = GridSearchCV(lasso, param, cv = 10).fit(X_train, y_train)
print('Best parameters are: ', tune.best_params_)
print('Best score are: ', tune.best_score_)

Best parameters are:  {'C': 100}
Best score are:  0.9330829301417538


In [0]:
best_lasso = LogisticRegression(max_iter = 1000, C = 100)
best_lasso.fit(X_train,y_train)
y_lass = best_lasso.predict(X_test)

In [82]:
print(" Best alpha of Lasso Regression: ", 100)
print()
print("Confusion matrix of lasso: ", confusion_matrix(y_test,y_lass))
print()
print("Accuracy of Lasso: ", accuracy_score(y_test,y_lass ))
print()
print("Coefficients of Lasso: ", best_lasso.coef_)

 Best alpha of Lasso Regression:  100

Confusion matrix of lasso:  [[275   2]
 [ 17   6]]

Accuracy of Lasso:  0.9366666666666666

Coefficients of Lasso:  [[-0.12231884 -0.13905365 -0.09229952  0.15519321  0.2467049   0.27082447
   0.19548685  0.10784374 -0.13050703 -0.1970268  -0.32535499 -0.30409911
  -0.29625953 -0.18922965 -0.08037865 -0.02494897 -0.00456472  0.29146061
   0.25989486  0.14447497  0.13443871 -0.06827533 -0.24797186 -0.35124759
  -0.14708435 -0.02849206  0.12076097  0.0554588   0.05739193 -0.11330449
  -0.26519867 -0.2719358  -0.17110056 -0.00534015  0.07858802  0.15111065
   0.20347777  0.17186854  0.09250831  0.19309758  0.15456366  0.01445395
  -0.13985451 -0.10874006 -0.05307217  0.01713077  0.09268864  0.13331427
   0.07060149 -0.0150161  -0.06952407  0.02204589  0.11960641 -0.0117969
  -0.0582138  -0.08049887  0.00056105 -0.02739972 -0.00899918 -0.01966029
   0.06343515 -0.0014711   0.01243777 -0.06226997  0.06433989 -0.03594739
  -0.01338944 -0.03350876  0.030

In [0]:
### Adaptive Lasso by transforming X
X_adap = X_train/np.abs(ridge.coef_)

In [86]:
adaptive_lasso = LogisticRegression(penalty ='l2', max_iter = 1000)
param = {'C':[0.1, 1, 10, 100]}
tune = GridSearchCV(adaptive_lasso, param, cv = 10).fit(X_adap, y_train)
print('Best parameters are: ', tune.best_params_)
print('Best score are: ', tune.best_score_)

Best parameters are:  {'C': 1}
Best score are:  0.9356760886172651


In [0]:
best_adapt = LogisticRegression(max_iter = 1000, C = 1)
best_adapt.fit(X_adap,y_train)
y_adapt = best_adapt.predict((X_test/np.abs(ridge.coef_)))

In [90]:
print(" Best alpha of Adaptive Lasso Regression: ", 1)
print()
print("Confusion matrix of lasso: ", confusion_matrix(y_test,y_adapt))
print()
print("Accuracy of Lasso: ", accuracy_score(y_test,y_adapt ))
print()
print("Coefficients of Lasso: ", best_adapt.coef_/np.abs(ridge.coef_))

 Best alpha of Adaptive Lasso Regression:  1

Confusion matrix of lasso:  [[277   0]
 [ 19   4]]

Accuracy of Lasso:  0.9366666666666666

Coefficients of Lasso:  [[-6.00247756e-01 -9.89756081e-03 -4.40112297e-03 -1.18330290e-03
  -4.25290678e-04 -4.84235039e-04 -8.05148336e-04 -3.53222757e-03
  -3.03183273e-03 -4.08233207e-02 -4.92505904e-03 -1.21070552e-02
  -1.77535188e-02 -3.97885656e-02 -1.22496727e-01 -1.35780178e-01
   5.48202956e-04  8.14450548e-04  3.27241036e-03  3.67321541e-02
  -9.46049666e-05 -3.54901721e-02 -6.24396148e-03 -7.58270730e-03
  -1.02638380e-02 -5.69625676e-02 -3.11774825e-02 -1.59090938e-02
  -7.09926521e-03 -2.18490769e-02 -5.01479617e-03 -7.17335147e-02
  -2.84511722e-03 -2.33432526e-03 -4.26968044e-04  1.47207472e-02
   2.00899298e-01  2.75663126e-01  1.32526093e-02  4.99429469e-02
   2.04609374e-02  8.27357112e-03  1.68056983e-03  6.50475638e-02
   1.23161519e-03  6.59354328e-03  3.82888615e-02  1.96158153e-03
   3.79785014e-03 -1.15846661e-03  8.69636356e

300

In [97]:
y_pred_ridge

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [99]:
y_adapt

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])